# Generated by Django 3.2.4 on 2021-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0010_auto_20210704_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pms',
            old_name='bu_individual_kpi_number',
            new_name='pms_bu_kpi_number',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='bu_individual_submit_end_date',
            new_name='pms_bu_submit_end_date',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='bu_individual_submit_result_date',
            new_name='pms_bu_submit_result_date',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='bu_individual_submit_start_date',
            new_name='pms_bu_submit_start_date',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='company_individual_kpi_number',
            new_name='pms_company_kpi_number',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='company_individual_submit_end_date',
            new_name='pms_company_submit_end_date',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='company_individual_submit_result_date',
            new_name='pms_company_submit_result_date',
        ),
        migrations.RenameField(
            model_name='pms',
            old_name='company_individual_submit_start_date',
            new_name='pms_company_submit_start_date',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya'), ('toyota_kenya', 'toyota_kenya'), ('cfao_agri', 'cfao_agri'), ('tydia', 'tydia')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T3', 'T3'), ('T6', 'T6'), ('T2', 'T2'), ('T1', 'T1'), ('T4', 'T4'), ('T5', 'T5')], help_text='user grade', max_length=5),
        ),
    ]
