# Generated by Django 3.2.4 on 2021-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0013_auto_20210705_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_kpi',
            name='company_kpi_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('cfao_agri', 'cfao_agri'), ('toyota_kenya', 'toyota_kenya'), ('tydia', 'tydia'), ('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T4', 'T4'), ('T2', 'T2'), ('T3', 'T3'), ('T6', 'T6'), ('T5', 'T5'), ('T1', 'T1')], help_text='user grade', max_length=5),
        ),
    ]
