# Generated by Django 3.2.4 on 2021-07-07 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0016_auto_20210707_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tamk', 'tamk'), ('toyota_kenya', 'toyota_kenya'), ('cfao_kenya', 'cfao_kenya'), ('cfao_agri', 'cfao_agri'), ('tydia', 'tydia')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T6', 'T6'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5')], help_text='user grade', max_length=5),
        ),
        migrations.CreateModel(
            name='matrix_checkin',
            fields=[
                ('matrix_checkin_id', models.UUIDField(default=uuid.uuid4, help_text='Unique identfier ci matrix', primary_key=True, serialize=False)),
                ('matrix_checkin_no', models.IntegerField(blank=True, help_text='No of Checkins', null=True)),
                ('matrix_checkin_score', models.FloatField(blank=True, help_text='Staff Grade', null=True)),
                ('matrix_pms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.pms')),
            ],
        ),
    ]
