# Generated by Django 3.2.4 on 2021-07-09 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0020_auto_20210709_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tydia', 'tydia'), ('toyota_kenya', 'toyota_kenya'), ('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya'), ('cfao_agri', 'cfao_agri')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T6', 'T6'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5')], help_text='user grade', max_length=5),
        ),
        migrations.CreateModel(
            name='evaluation_responses',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response', models.CharField(blank=True, choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree')], default=None, max_length=20)),
                ('response_score', models.FloatField()),
                ('response_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.evaluation')),
            ],
        ),
    ]
