# Generated by Django 3.2.3 on 2021-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamk', '0004_auto_20210606_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('toyota_kenya', 'toyota_kenya'), ('tydia', 'tydia'), ('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya'), ('cfao_agri', 'cfao_agri')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T4', 'T4'), ('T5', 'T5'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T6', 'T6')], help_text='user grade', max_length=5),
        ),
    ]
