# Generated by Django 3.2.3 on 2021-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0004_auto_20210522_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('cfao_agri', 'cfao_agri'), ('tamk', 'tamk'), ('toyota_kenya', 'toyota_kenya'), ('tydia', 'tydia'), ('cfao_kenya', 'cfao_kenya')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T1', 'T1'), ('T6', 'T6')], help_text='user grade', max_length=5),
        ),
    ]
