# Generated by Django 3.2.4 on 2021-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0011_auto_20210704_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_april_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_august_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_december_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_february_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_january_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_july_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_june_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_march_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_may_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_november_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_october_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AddField(
            model_name='bu_kpi',
            name='bu_kpi_september_score_approve',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=13),
        ),
        migrations.AlterField(
            model_name='bu_kpi',
            name='bu_kpi_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Addition', 'Addition'), ('cumulative', 'cumulative'), ('YTD', 'YTD')], default='cumulative', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tamk', 'tamk'), ('tydia', 'tydia'), ('cfao_kenya', 'cfao_kenya'), ('toyota_kenya', 'toyota_kenya'), ('cfao_agri', 'cfao_agri')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T6', 'T6'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T2', 'T2')], help_text='user grade', max_length=5),
        ),
    ]
