# Generated by Django 3.2.4 on 2021-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0012_auto_20210705_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_kpi',
            old_name='company_kpi_pms_id',
            new_name='company_kpi_pms',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('toyota_kenya', 'toyota_kenya'), ('cfao_agri', 'cfao_agri'), ('tydia', 'tydia'), ('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T5', 'T5'), ('T6', 'T6'), ('T1', 'T1'), ('T4', 'T4'), ('T2', 'T2'), ('T3', 'T3')], help_text='user grade', max_length=5),
        ),
    ]
