# Generated by Django 3.2.4 on 2021-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0018_auto_20210707_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_months',
            name='kpi_months_class',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('BU', 'BU'), ('Individual', 'Individual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('toyota_kenya', 'toyota_kenya'), ('cfao_agri', 'cfao_agri'), ('cfao_kenya', 'cfao_kenya'), ('tydia', 'tydia'), ('tamk', 'tamk')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T5', 'T5'), ('T6', 'T6'), ('T3', 'T3'), ('T4', 'T4')], help_text='user grade', max_length=5),
        ),
    ]
