# Generated by Django 3.2.4 on 2021-07-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0019_auto_20210707_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_use',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('cfao_kenya', 'cfao_kenya'), ('tamk', 'tamk'), ('cfao_agri', 'cfao_agri'), ('toyota_kenya', 'toyota_kenya'), ('tydia', 'tydia')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T3', 'T3'), ('T2', 'T2'), ('T6', 'T6'), ('T1', 'T1'), ('T5', 'T5'), ('T4', 'T4')], help_text='user grade', max_length=5),
        ),
    ]
