# Generated by Django 3.2.4 on 2021-07-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0022_auto_20210709_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_company',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_email_address',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T4', 'T4'), ('T2', 'T2'), ('T3', 'T3'), ('T1', 'T1'), ('T6', 'T6'), ('T5', 'T5')], help_text='user grade', max_length=5),
        ),
    ]
