# Generated by Django 4.0.3 on 2022-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_user_name',
            field=models.CharField(default='Staff', max_length=50),
        ),
    ]
