# Generated by Django 4.0.2 on 2022-02-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Staff_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
