# Generated by Django 4.0.3 on 2022-04-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_passwordchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='matrix_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.staffgrades'),
        ),
    ]
