# Generated by Django 4.0.2 on 2022-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='error_code',
            field=models.CharField(default='Err001', max_length=10),
        ),
    ]
