# Generated by Django 4.0.2 on 2022-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_error_error_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
