# Generated by Django 4.0.3 on 2022-05-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_pms_pms_cap_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_bu_override',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.level'),
        ),
    ]
