# Generated by Django 4.0.2 on 2022-02-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_delete_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory'),
        ),
    ]
