# Generated by Django 4.0.2 on 2022-02-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_staff_staff_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_kpi', models.CharField(choices=[('Annual Target', 'Annual Target'), ('Monthly Target', 'Monthly Target'), ('BSC', 'BSC')], default='Annual Target', max_length=20)),
                ('type_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory')),
                ('type_pms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.pms')),
            ],
        ),
    ]
