# Generated by Django 4.0.3 on 2022-07-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillarsApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_minimum_kpis', models.IntegerField()),
                ('application_maximum_kpis', models.IntegerField()),
                ('application_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pillar_application_level_category', to='Site.levelcategory')),
                ('application_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pillar_application_staff_grade', to='Site.staffgrades')),
                ('application_pillar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pillar_application_select_pillar', to='Site.staffgrades')),
                ('application_pms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.pms')),
            ],
        ),
    ]
