# Generated by Django 4.0.2 on 2022-02-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_kpitype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='kpi_target',
            field=models.FloatField(default=0),
        ),
    ]
