# Generated by Django 4.0.2 on 2022-02-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_alter_kpi_kpi_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelcategory',
            name='category_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.company'),
        ),
    ]
