# Generated by Django 4.0.3 on 2022-07-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDPCycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_minimum_required_competency', models.IntegerField()),
                ('cycle_maximum_required_competency', models.IntegerField()),
                ('cycle_start', models.DateTimeField()),
                ('cycle_end', models.DateTimeField()),
                ('cycle_company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.company')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('competency_id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_name', models.CharField(max_length=100)),
                ('competency_description', models.TextField(blank=True, null=True)),
                ('competency_cycle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.cdpcycle')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory')),
                ('assignment_competency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.competency')),
                ('assignment_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.staffgrades')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCompetency',
            fields=[
                ('applied_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_competency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.competency')),
                ('applied_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.staff')),
            ],
        ),
    ]
