# Generated by Django 4.0.2 on 2022-02-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_levelcategory_category_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcategory',
            name='category_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.company'),
        ),
    ]
