# Generated by Django 4.0.3 on 2022-07-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_cdpcycle_competency_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIApprovalStages',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_approval', models.CharField(choices=[('Initial', 'Initial'), ('Intermediate', 'Intermediate'), ('Final', 'Final')], max_length=15)),
                ('stage_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory')),
                ('stage_pms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.pms')),
            ],
        ),
        migrations.CreateModel(
            name='KPIApprovals',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Edit', 'Edit Mode')], default=None, max_length=10)),
                ('approval_date', models.DateTimeField(auto_now=True)),
                ('approval_head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.staff')),
                ('approval_kpi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.kpi')),
            ],
        ),
    ]
