# Generated by Django 4.0.2 on 2022-03-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_alter_levelcategory_category_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcategory',
            name='category_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.company'),
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('help_status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Resolved', 'Closed')], max_length=20)),
                ('help_requested', models.TextField()),
                ('help_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Site.staff')),
            ],
        ),
    ]
