# Generated by Django 4.0.2 on 2022-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_alter_levelcategory_category_company_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_close_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='help',
            name='help_last_edit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='help',
            name='help_log_date',
            field=models.DateTimeField(null=True),
        ),
    ]
