# Generated by Django 4.0.3 on 2022-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiapprovals',
            name='approval_submit_edit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kpiapprovals',
            name='approval_date',
            field=models.DateTimeField(),
        ),
    ]
