# Generated by Django 4.0.3 on 2022-07-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiapprovals',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
