# Generated by Django 4.0.2 on 2022-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_help_help_close_edit_help_help_last_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_category',
            field=models.CharField(choices=[('KPI', 'KPI'), ('Check-In', 'Check-In'), ('Assessment', 'Assessment'), ('Reports', 'Reports'), ('Results', 'Results'), ('Other', 'Other')], default='KPI', max_length=20),
        ),
    ]
