# Generated by Django 4.0.3 on 2022-07-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdpcycle',
            name='cycle_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
