# Generated by Django 4.0.2 on 2022-03-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_help_help_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
