# Generated by Django 4.0.2 on 2022-03-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_staff_staff_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='matrix_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Site.levelcategory'),
        ),
    ]
