# Generated by Django 4.0.2 on 2022-03-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0015_matrix_matrix_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='matrix_assessment_weight',
            field=models.FloatField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_bu_weight',
            field=models.FloatField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_checkin_weight',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_company_weight',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='matrix_kpi_weight',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
