# Generated by Django 3.2.3 on 2021-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_agri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tydia', 'tydia'), ('cfao_kenya', 'cfao_kenya'), ('toyota_kenya', 'toyota_kenya'), ('tamk', 'tamk'), ('cfao_agri', 'cfao_agri')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T1', 'T1'), ('T2', 'T2'), ('T6', 'T6')], help_text='user grade', max_length=5),
        ),
    ]
