# Generated by Django 3.2.3 on 2021-06-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_agri', '0004_auto_20210606_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('toyota_kenya', 'toyota_kenya'), ('tydia', 'tydia'), ('cfao_agri', 'cfao_agri'), ('tamk', 'tamk'), ('cfao_kenya', 'cfao_kenya')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T4', 'T4'), ('T2', 'T2'), ('T1', 'T1'), ('T3', 'T3'), ('T6', 'T6'), ('T5', 'T5')], help_text='user grade', max_length=5),
        ),
    ]
