# Generated by Django 3.2.9 on 2021-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkIn_submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
