# Generated by Django 3.2.9 on 2021-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0002_alter_checkin_checkin_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkIn_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pms',
            name='pms_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionresponses',
            name='response_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
