# Generated by Django 3.2.9 on 2021-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0003_auto_20211106_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponses',
            name='response_submitted',
            field=models.FloatField(default=None),
        ),
    ]
