# Generated by Django 3.2.9 on 2021-11-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0004_questionresponses_response_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponses',
            name='response_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.questions'),
        ),
    ]
