# Generated by Django 3.2.9 on 2021-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0005_alter_questionresponses_response_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_max_score',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_min_score',
            field=models.FloatField(default=0),
        ),
    ]
