# Generated by Django 3.2.9 on 2021-11-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0006_auto_20211109_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionCheckin',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_one_results', models.IntegerField(default=0)),
                ('submission_two_results', models.IntegerField(default=0)),
                ('submission_three_results', models.IntegerField(default=10)),
                ('submission_four_results', models.IntegerField(default=20)),
                ('submission_five_results', models.IntegerField(default=30)),
                ('submission_six_results', models.IntegerField(default=40)),
                ('submission_seven_results', models.IntegerField(default=50)),
                ('submission_eight_results', models.IntegerField(default=60)),
                ('submission_nine_results', models.IntegerField(default=70)),
                ('submission_ten_results', models.IntegerField(default=80)),
                ('submission_eleven_results', models.IntegerField(default=90)),
                ('submission_twelve_results', models.IntegerField(default=100)),
                ('submission_april_checkin_calculation', models.BooleanField(default=True)),
                ('submission_may_checkin_calculation', models.BooleanField(default=True)),
                ('submission_june_checkin_calculation', models.BooleanField(default=True)),
                ('submission_july_checkin_calculation', models.BooleanField(default=True)),
                ('submission_august_checkin_calculation', models.BooleanField(default=True)),
                ('submission_september_checkin_calculation', models.BooleanField(default=True)),
                ('submission_october_checkin_calculation', models.BooleanField(default=True)),
                ('submission_november_checkin_calculation', models.BooleanField(default=True)),
                ('submission_december_checkin_calculation', models.BooleanField(default=True)),
                ('submission_january_checkin_calculation', models.BooleanField(default=True)),
                ('submission_february_checkin_calculation', models.BooleanField(default=True)),
                ('submission_march_checkin_calculation', models.BooleanField(default=True)),
                ('submission_level_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.levelcategory')),
                ('submission_pms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.pms')),
            ],
        ),
    ]
