# Generated by Django 3.2.9 on 2021-11-15 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0007_submissioncheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('matrix_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('matrix_checkin_weight', models.FloatField(blank=True, null=True)),
                ('matrix_kpi_weight', models.FloatField(blank=True, null=True)),
                ('matrix_assessment_weight', models.FloatField(blank=True, null=True)),
                ('matrix_category1_weight_no', models.FloatField(default=0)),
                ('matrix_category2_weight_no', models.FloatField(default=0)),
                ('matrix_category3_weight_no', models.FloatField(default=0)),
                ('matrix_category4_weight_no', models.FloatField(default=0)),
                ('matrix_category5_weight_no', models.FloatField(default=0)),
                ('matrix_category1_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cfao_kenya_cat1_weight', to='cfao_kenya.levelcategory')),
                ('matrix_category2_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cfao_kenya_cat2_weight', to='cfao_kenya.levelcategory')),
                ('matrix_category3_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cfao_kenya_cat3_weight', to='cfao_kenya.levelcategory')),
                ('matrix_category4_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cfao_kenya_cat4_weight', to='cfao_kenya.levelcategory')),
                ('matrix_category5_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cfao_kenya_cat5_weight', to='cfao_kenya.levelcategory')),
                ('matrix_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.staffgrades')),
                ('matrix_pms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cfao_kenya.pms')),
            ],
        ),
    ]
