# Generated by Django 3.2.3 on 2021-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfao_kenya', '0008_auto_20210606_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pms',
            name='bu_individual_submit_result_date',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='pms',
            name='company_individual_submit_result_date',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='pms',
            name='pms_individual_submit_results_date',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_company',
            field=models.CharField(blank=True, choices=[('tydia', 'tydia'), ('cfao_kenya', 'cfao_kenya'), ('cfao_agri', 'cfao_agri'), ('toyota_kenya', 'toyota_kenya'), ('tamk', 'tamk')], help_text='user grade', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_grade',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], help_text='user grade', max_length=5),
        ),
    ]
