# Generated by Django 4.0.3 on 2022-07-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_checkin_check_in_declaration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillarsapplications',
            name='application_pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pillar_application_select_pillar', to='Site.bscpillar'),
        ),
    ]
