# Generated by Django 4.0.3 on 2022-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_alter_matrix_matrix_assessment_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_reference_key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
